name: okoul_movie_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  glassmorphism: ^3.0.0
  device_preview: ^1.0.0
  get:
  get_storage:
  google_fonts:
  widget_mask:
  zoom_tap_animation:
  flutter_animated_cards: ^0.0.2
  carousel_slider: ^4.2.1
  flutter_animate: ^0.3.0
  shimmer:
  lottie:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/mask/

